/** Extra brand / snack / fast-food presets (merged into PRESET_CATALOG). */
import type { CatalogPreset } from "./presetCatalog.js";

/** Jersey Mike's, Oreos, SunChips, snacks, and common fast-food meals. Macros are approximate label/menu values. */
export const PRESET_CATALOG_EXTRAS: CatalogPreset[] = [
  // ——— Jersey Mike's ———
  {
    id: "preset-jm-13-reg-rosemary-mikes-way-mayo-mustard-relish",
    name: "#13 Original Italian Regular · Rosemary · Mike's Way + mayo, yellow mustard, pepper relish",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 1035,
    protein: 46,
    carbs: 76,
    fat: 58,
    fiber: 4,
    sugar: 10,
    sodium: 2850,
    aliases: [
      "13",
      "number 13",
      "#13",
      "original italian",
      "real deal",
      "jm",
      "jersey mikes",
      "rosemary",
      "mikes way",
      "mike's way",
      "mayo",
      "mustard",
      "pepper relish",
      "sub",
      "sandwich",
    ],
  },
  {
    id: "preset-jm-13-reg-rosemary-mikes-way",
    name: "#13 Original Italian Regular · Rosemary · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 970,
    protein: 46,
    carbs: 72,
    fat: 55,
    fiber: 5,
    sugar: 11,
    sodium: 2630,
    aliases: ["13", "#13", "original italian", "jm", "rosemary", "mikes way"],
  },
  {
    id: "preset-jm-13-reg-white-mikes-way",
    name: "#13 Original Italian Regular · White · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 850,
    protein: 45,
    carbs: 66,
    fat: 42,
    fiber: 4,
    sugar: 9,
    sodium: 2500,
    aliases: ["13", "white bread", "jm"],
  },
  {
    id: "preset-jm-7-reg-turkey-provolone",
    name: "#7 Turkey & Provolone Regular · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 720,
    protein: 48,
    carbs: 62,
    fat: 30,
    fiber: 4,
    sugar: 8,
    sodium: 2200,
    aliases: ["7", "turkey", "provolone", "jm"],
  },
  {
    id: "preset-jm-8-reg-club",
    name: "#8 Club Super Regular · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 780,
    protein: 50,
    carbs: 64,
    fat: 34,
    fiber: 4,
    sugar: 8,
    sodium: 2400,
    aliases: ["8", "club", "ham turkey", "jm"],
  },
  {
    id: "preset-jm-9-reg-roast-beef",
    name: "#9 Roast Beef & Provolone Regular · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 740,
    protein: 48,
    carbs: 60,
    fat: 32,
    fiber: 4,
    sugar: 7,
    sodium: 2300,
    aliases: ["9", "roast beef", "jm"],
  },
  {
    id: "preset-jm-3-reg-ham-provolone",
    name: "#3 Ham & Provolone Regular · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 700,
    protein: 42,
    carbs: 62,
    fat: 28,
    fiber: 4,
    sugar: 8,
    sodium: 2300,
    aliases: ["3", "ham", "jm"],
  },
  {
    id: "preset-jm-56-reg-blt",
    name: "#56 BLT Regular · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 760,
    protein: 28,
    carbs: 58,
    fat: 44,
    fiber: 4,
    sugar: 7,
    sodium: 1800,
    aliases: ["56", "blt", "bacon", "jm"],
  },
  {
    id: "preset-jm-14-reg-chipotle-cheese-steak",
    name: "#14 Chipotle Cheese Steak Regular",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 890,
    protein: 52,
    carbs: 68,
    fat: 42,
    fiber: 4,
    sugar: 8,
    sodium: 2100,
    aliases: ["14", "chipotle", "cheesesteak", "steak", "jm"],
  },
  {
    id: "preset-jm-43-reg-chicken-philly",
    name: "#43 Chicken Philly Regular",
    brand: "Jersey Mike's",
    servingLabel: "sub",
    calories: 820,
    protein: 50,
    carbs: 66,
    fat: 36,
    fiber: 4,
    sugar: 8,
    sodium: 2000,
    aliases: ["43", "chicken philly", "jm"],
  },
  {
    id: "preset-jm-mini-13",
    name: "#13 Original Italian Mini · Mike's Way",
    brand: "Jersey Mike's",
    servingLabel: "mini",
    calories: 520,
    protein: 26,
    carbs: 40,
    fat: 28,
    fiber: 3,
    sugar: 6,
    sodium: 1450,
    aliases: ["mini 13", "kid", "jm"],
  },

  // ——— Oreo (per cookie — set amount to cookie count) ———
  {
    id: "preset-oreo-regular",
    name: "Oreo cookie",
    brand: "Oreo",
    servingLabel: "cookie",
    calories: 53,
    protein: 0.5,
    carbs: 8.3,
    fat: 2.3,
    sugar: 4.7,
    fiber: 0.3,
    sodium: 45,
    aliases: ["oreos", "regular oreo", "classic oreo", "cookie"],
  },
  {
    id: "preset-oreo-double-stuf",
    name: "Oreo Double Stuf cookie",
    brand: "Oreo",
    servingLabel: "cookie",
    calories: 70,
    protein: 0.6,
    carbs: 10,
    fat: 3.3,
    sugar: 6.3,
    fiber: 0.3,
    sodium: 55,
    aliases: ["double stuffed", "double stuff", "double stuf", "oreos"],
  },
  {
    id: "preset-oreo-thins",
    name: "Oreo Thins cookie",
    brand: "Oreo",
    servingLabel: "cookie",
    calories: 35,
    protein: 0.4,
    carbs: 5.3,
    fat: 1.5,
    sugar: 3.2,
    fiber: 0.2,
    sodium: 30,
    aliases: ["thin", "thins", "oreo thin", "oreos"],
  },
  {
    id: "preset-oreo-mega-stuf",
    name: "Oreo Mega Stuf cookie",
    brand: "Oreo",
    servingLabel: "cookie",
    calories: 90,
    protein: 0.7,
    carbs: 12,
    fat: 4.5,
    sugar: 8,
    fiber: 0.3,
    sodium: 65,
    aliases: ["mega", "mega stuffed"],
  },

  // ——— SunChips ———
  {
    id: "preset-sunchips-original",
    name: "SunChips Original",
    brand: "SunChips",
    servingLabel: "oz (about 15 chips)",
    calories: 140,
    protein: 2,
    carbs: 19,
    fat: 6,
    fiber: 2,
    sugar: 2,
    sodium: 120,
    aliases: ["sun chips", "sunchip", "original"],
  },
  {
    id: "preset-sunchips-harvest-cheddar",
    name: "SunChips Harvest Cheddar",
    brand: "SunChips",
    servingLabel: "oz (about 15 chips)",
    calories: 140,
    protein: 2,
    carbs: 18,
    fat: 6,
    fiber: 2,
    sugar: 2,
    sodium: 180,
    aliases: ["sun chips", "cheddar", "harvest"],
  },
  {
    id: "preset-sunchips-french-onion",
    name: "SunChips French Onion",
    brand: "SunChips",
    servingLabel: "oz (about 15 chips)",
    calories: 140,
    protein: 2,
    carbs: 18,
    fat: 6,
    fiber: 2,
    sugar: 2,
    sodium: 170,
    aliases: ["sun chips", "onion"],
  },
  {
    id: "preset-sunchips-garden-salsa",
    name: "SunChips Garden Salsa",
    brand: "SunChips",
    servingLabel: "oz (about 15 chips)",
    calories: 140,
    protein: 2,
    carbs: 19,
    fat: 6,
    fiber: 2,
    sugar: 2,
    sodium: 150,
    aliases: ["sun chips", "salsa"],
  },
  {
    id: "preset-sunchips-sweet-potato",
    name: "SunChips Sweet Potato",
    brand: "SunChips",
    servingLabel: "oz",
    calories: 140,
    protein: 2,
    carbs: 19,
    fat: 6,
    fiber: 2,
    sugar: 3,
    sodium: 140,
    aliases: ["sun chips", "sweet potato"],
  },

  // ——— Chips / crisps ———
  {
    id: "preset-lays-classic",
    name: "Classic Potato Chips",
    brand: "Lay's",
    servingLabel: "oz (about 15 chips)",
    calories: 160,
    protein: 2,
    carbs: 15,
    fat: 10,
    sugar: 0,
    sodium: 170,
    aliases: ["lays", "potato chips", "chips"],
  },
  {
    id: "preset-lays-bbq",
    name: "Barbecue Potato Chips",
    brand: "Lay's",
    servingLabel: "oz",
    calories: 160,
    protein: 2,
    carbs: 15,
    fat: 10,
    sugar: 2,
    sodium: 170,
    aliases: ["bbq", "barbeque", "chips"],
  },
  {
    id: "preset-doritos-nacho",
    name: "Nacho Cheese",
    brand: "Doritos",
    servingLabel: "oz (about 12 chips)",
    calories: 150,
    protein: 2,
    carbs: 18,
    fat: 8,
    sugar: 1,
    sodium: 210,
    aliases: ["nacho", "chips", "tortilla"],
  },
  {
    id: "preset-doritos-cool-ranch",
    name: "Cool Ranch",
    brand: "Doritos",
    servingLabel: "oz",
    calories: 140,
    protein: 2,
    carbs: 18,
    fat: 7,
    sugar: 1,
    sodium: 200,
    aliases: ["ranch", "chips"],
  },
  {
    id: "preset-cheetos-crunchy",
    name: "Crunchy Cheetos",
    brand: "Cheetos",
    servingLabel: "oz",
    calories: 160,
    protein: 2,
    carbs: 15,
    fat: 10,
    sugar: 0,
    sodium: 250,
    aliases: ["cheese puffs", "crunchy"],
  },
  {
    id: "preset-ritz-crackers",
    name: "Ritz Crackers",
    brand: "Ritz",
    servingLabel: "5 crackers",
    calories: 80,
    protein: 1,
    carbs: 10,
    fat: 4,
    sugar: 1,
    sodium: 135,
    aliases: ["crackers"],
  },
  {
    id: "preset-goldfish-cheddar",
    name: "Cheddar Goldfish",
    brand: "Pepperidge Farm",
    servingLabel: "55 pieces (30g)",
    calories: 140,
    protein: 3,
    carbs: 20,
    fat: 5,
    sugar: 0,
    sodium: 250,
    aliases: ["goldfish", "crackers"],
  },
  {
    id: "preset-pretzel-rold-gold",
    name: "Tiny Twists Pretzels",
    brand: "Rold Gold",
    servingLabel: "oz (about 20)",
    calories: 110,
    protein: 3,
    carbs: 23,
    fat: 1,
    sugar: 1,
    sodium: 450,
    aliases: ["pretzels"],
  },
  {
    id: "preset-popcorners-white-cheddar",
    name: "White Cheddar Popcorners",
    brand: "Popcorners",
    servingLabel: "oz",
    calories: 130,
    protein: 2,
    carbs: 18,
    fat: 5,
    sugar: 1,
    sodium: 190,
    aliases: ["popcorn chips"],
  },
  {
    id: "preset-quest-chips-bbq",
    name: "Protein Chips BBQ",
    brand: "Quest",
    servingLabel: "bag (32g)",
    calories: 140,
    protein: 18,
    carbs: 5,
    fat: 5,
    fiber: 1,
    sugar: 1,
    sodium: 330,
    aliases: ["protein chips"],
  },

  // ——— Candy / cookies / bars ———
  {
    id: "preset-snickers",
    name: "Snickers bar",
    brand: "Snickers",
    servingLabel: "bar (52g)",
    calories: 250,
    protein: 4,
    carbs: 33,
    fat: 12,
    sugar: 27,
    sodium: 120,
    aliases: ["candy bar"],
  },
  {
    id: "preset-kitkat",
    name: "KitKat bar (4 fingers)",
    brand: "KitKat",
    servingLabel: "bar",
    calories: 210,
    protein: 3,
    carbs: 26,
    fat: 11,
    sugar: 21,
    sodium: 30,
    aliases: ["kit kat"],
  },
  {
    id: "preset-reeses-cups",
    name: "Reese's Peanut Butter Cups (2)",
    brand: "Reese's",
    servingLabel: "2 cups",
    calories: 210,
    protein: 5,
    carbs: 24,
    fat: 13,
    sugar: 21,
    sodium: 150,
    aliases: ["reese", "peanut butter cups"],
  },
  {
    id: "preset-twix",
    name: "Twix (2 sticks)",
    brand: "Twix",
    servingLabel: "pack",
    calories: 250,
    protein: 2,
    carbs: 33,
    fat: 12,
    sugar: 24,
    sodium: 100,
  },
  {
    id: "preset-nature-valley-oats-honey",
    name: "Crunchy Oats 'n Honey",
    brand: "Nature Valley",
    servingLabel: "2 bars (packet)",
    calories: 190,
    protein: 3,
    carbs: 29,
    fat: 7,
    sugar: 11,
    fiber: 2,
    sodium: 160,
    aliases: ["granola bar"],
  },
  {
    id: "preset-clif-bar-chocolate-chip",
    name: "Chocolate Chip Clif Bar",
    brand: "Clif",
    servingLabel: "bar",
    calories: 250,
    protein: 9,
    carbs: 44,
    fat: 5,
    fiber: 4,
    sugar: 22,
    sodium: 150,
    aliases: ["cliff bar", "energy bar"],
  },
  {
    id: "preset-kind-dark-chocolate-nuts",
    name: "Dark Chocolate Nuts & Sea Salt",
    brand: "KIND",
    servingLabel: "bar",
    calories: 200,
    protein: 6,
    carbs: 16,
    fat: 15,
    fiber: 3,
    sugar: 5,
    sodium: 125,
    aliases: ["kind bar"],
  },
  {
    id: "preset-rxbar-chocolate-sea-salt",
    name: "Chocolate Sea Salt",
    brand: "RXBAR",
    servingLabel: "bar",
    calories: 210,
    protein: 12,
    carbs: 23,
    fat: 9,
    fiber: 5,
    sugar: 13,
    sodium: 270,
    aliases: ["rx bar"],
  },

  // ——— Grocery snacks / staples ———
  {
    id: "preset-string-cheese",
    name: "String cheese",
    brand: "Generic",
    servingLabel: "stick",
    calories: 80,
    protein: 7,
    carbs: 1,
    fat: 6,
    sodium: 200,
    aliases: ["mozzarella stick", "cheese stick"],
  },
  {
    id: "preset-babybel",
    name: "Mini Babybel Original",
    brand: "Babybel",
    servingLabel: "wheel",
    calories: 70,
    protein: 5,
    carbs: 0,
    fat: 6,
    sodium: 160,
  },
  {
    id: "preset-beef-jerky-oz",
    name: "Beef jerky",
    brand: "Generic",
    servingLabel: "oz",
    calories: 80,
    protein: 13,
    carbs: 3,
    fat: 1.5,
    sugar: 3,
    sodium: 480,
    aliases: ["jerky"],
  },
  {
    id: "preset-trail-mix-oz",
    name: "Trail mix (nuts & raisins)",
    brand: "Generic",
    servingLabel: "oz",
    calories: 140,
    protein: 4,
    carbs: 12,
    fat: 9,
    sugar: 8,
    fiber: 2,
    sodium: 50,
    aliases: ["mixed nuts"],
  },
  {
    id: "preset-almonds-oz",
    name: "Almonds",
    brand: "Generic",
    servingLabel: "oz (about 23)",
    calories: 160,
    protein: 6,
    carbs: 6,
    fat: 14,
    fiber: 4,
    sugar: 1,
    sodium: 0,
  },
  {
    id: "preset-popcorn-air-popped",
    name: "Air-popped popcorn",
    brand: "Generic",
    servingLabel: "3 cups",
    calories: 90,
    protein: 3,
    carbs: 19,
    fat: 1,
    fiber: 4,
    sugar: 0,
    sodium: 2,
    aliases: ["popcorn"],
  },
  {
    id: "preset-skin-popcorn",
    name: "Smartfood White Cheddar",
    brand: "Smartfood",
    servingLabel: "oz",
    calories: 160,
    protein: 3,
    carbs: 14,
    fat: 10,
    sugar: 2,
    sodium: 290,
    aliases: ["cheddar popcorn"],
  },
  {
    id: "preset-applesauce-cup",
    name: "Applesauce cup (unsweetened)",
    brand: "Generic",
    servingLabel: "cup (4oz)",
    calories: 50,
    protein: 0,
    carbs: 13,
    fat: 0,
    sugar: 11,
    fiber: 1,
    sodium: 0,
  },
  {
    id: "preset-fruit-cup",
    name: "Fruit cup in juice",
    brand: "Generic",
    servingLabel: "cup (4oz)",
    calories: 60,
    protein: 0,
    carbs: 15,
    fat: 0,
    sugar: 14,
    sodium: 5,
  },
  {
    id: "preset-greek-yogurt-cup-nonfat",
    name: "Nonfat Greek yogurt plain",
    brand: "Generic",
    servingLabel: "cup (170g)",
    calories: 100,
    protein: 17,
    carbs: 6,
    fat: 0,
    sugar: 4,
    sodium: 55,
    aliases: ["yogurt"],
  },
  {
    id: "preset-cottage-cheese-half-cup",
    name: "Low-fat cottage cheese",
    brand: "Generic",
    servingLabel: "1/2 cup",
    calories: 90,
    protein: 13,
    carbs: 4,
    fat: 2.5,
    sugar: 4,
    sodium: 370,
  },
  {
    id: "preset-hard-boiled-egg",
    name: "Hard-boiled egg",
    brand: "Generic",
    servingLabel: "egg",
    calories: 70,
    protein: 6,
    carbs: 0.5,
    fat: 5,
    sodium: 65,
    aliases: ["egg"],
  },
  {
    id: "preset-banana",
    name: "Banana (medium)",
    brand: "Generic",
    servingLabel: "banana",
    calories: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
    fiber: 3,
    sugar: 14,
    sodium: 1,
  },
  {
    id: "preset-apple",
    name: "Apple (medium)",
    brand: "Generic",
    servingLabel: "apple",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0,
    fiber: 4,
    sugar: 19,
    sodium: 2,
  },
  {
    id: "preset-rice-cake-plain",
    name: "Plain rice cake",
    brand: "Generic",
    servingLabel: "cake",
    calories: 35,
    protein: 0.7,
    carbs: 7,
    fat: 0,
    sodium: 0,
  },

  // ——— Fast food ———
  {
    id: "preset-mcd-big-mac",
    name: "Big Mac",
    brand: "McDonald's",
    servingLabel: "sandwich",
    calories: 590,
    protein: 25,
    carbs: 46,
    fat: 34,
    sugar: 9,
    sodium: 1050,
    aliases: ["mcdonalds", "mcd", "burger"],
  },
  {
    id: "preset-mcd-quarter-pounder-cheese",
    name: "Quarter Pounder with Cheese",
    brand: "McDonald's",
    servingLabel: "sandwich",
    calories: 520,
    protein: 30,
    carbs: 42,
    fat: 26,
    sugar: 10,
    sodium: 1140,
    aliases: ["qp", "quarter pounder", "mcdonalds"],
  },
  {
    id: "preset-mcd-mcchicken",
    name: "McChicken",
    brand: "McDonald's",
    servingLabel: "sandwich",
    calories: 400,
    protein: 14,
    carbs: 39,
    fat: 21,
    sugar: 5,
    sodium: 720,
    aliases: ["mcdonalds", "chicken sandwich"],
  },
  {
    id: "preset-mcd-fries-medium",
    name: "French Fries (medium)",
    brand: "McDonald's",
    servingLabel: "serving",
    calories: 320,
    protein: 5,
    carbs: 43,
    fat: 15,
    sodium: 260,
    aliases: ["fries", "mcdonalds"],
  },
  {
    id: "preset-mcd-nuggets-6",
    name: "Chicken McNuggets (6 pc)",
    brand: "McDonald's",
    servingLabel: "6 pieces",
    calories: 250,
    protein: 14,
    carbs: 15,
    fat: 15,
    sodium: 500,
    aliases: ["nuggets", "mcdonalds"],
  },
  {
    id: "preset-wendy-dave-single",
    name: "Dave's Single",
    brand: "Wendy's",
    servingLabel: "burger",
    calories: 590,
    protein: 30,
    carbs: 39,
    fat: 34,
    sugar: 8,
    sodium: 1180,
    aliases: ["wendys", "dave single"],
  },
  {
    id: "preset-wendy-spicy-chicken",
    name: "Spicy Chicken Sandwich",
    brand: "Wendy's",
    servingLabel: "sandwich",
    calories: 500,
    protein: 28,
    carbs: 45,
    fat: 21,
    sugar: 6,
    sodium: 1220,
    aliases: ["wendys", "spicy chicken"],
  },
  {
    id: "preset-bk-whopper",
    name: "Whopper",
    brand: "Burger King",
    servingLabel: "sandwich",
    calories: 670,
    protein: 30,
    carbs: 54,
    fat: 39,
    sugar: 12,
    sodium: 980,
    aliases: ["bk", "burger king"],
  },
  {
    id: "preset-bk-chicken-fries-9",
    name: "Chicken Fries (9 pc)",
    brand: "Burger King",
    servingLabel: "9 pieces",
    calories: 280,
    protein: 13,
    carbs: 20,
    fat: 17,
    sodium: 770,
    aliases: ["bk", "chicken fries"],
  },
  {
    id: "preset-subway-turkey-6",
    name: "Oven Roasted Turkey 6\" (no cheese/sauce)",
    brand: "Subway",
    servingLabel: "6-inch",
    calories: 280,
    protein: 18,
    carbs: 46,
    fat: 3.5,
    fiber: 5,
    sugar: 7,
    sodium: 760,
    aliases: ["sub", "turkey sub"],
  },
  {
    id: "preset-subway-italian-bmt-6",
    name: "Italian B.M.T. 6\"",
    brand: "Subway",
    servingLabel: "6-inch",
    calories: 410,
    protein: 19,
    carbs: 44,
    fat: 18,
    sugar: 7,
    sodium: 1360,
    aliases: ["bmt", "italian"],
  },
  {
    id: "preset-chipotle-chicken-bowl",
    name: "Chicken burrito bowl (rice, beans, salsa, cheese, lettuce)",
    brand: "Chipotle",
    servingLabel: "bowl",
    calories: 720,
    protein: 48,
    carbs: 70,
    fat: 27,
    fiber: 12,
    sugar: 5,
    sodium: 1600,
    aliases: ["burrito bowl", "chicken bowl"],
  },
  {
    id: "preset-taco-bell-crunchy-taco",
    name: "Crunchy Taco",
    brand: "Taco Bell",
    servingLabel: "taco",
    calories: 170,
    protein: 8,
    carbs: 13,
    fat: 9,
    sugar: 1,
    sodium: 310,
    aliases: ["taco"],
  },
  {
    id: "preset-taco-bell-bean-burrito",
    name: "Bean Burrito",
    brand: "Taco Bell",
    servingLabel: "burrito",
    calories: 350,
    protein: 12,
    carbs: 53,
    fat: 10,
    fiber: 9,
    sugar: 3,
    sodium: 1030,
  },
  {
    id: "preset-chickfila-sandwich",
    name: "Chicken Sandwich",
    brand: "Chick-fil-A",
    servingLabel: "sandwich",
    calories: 440,
    protein: 29,
    carbs: 41,
    fat: 17,
    sugar: 6,
    sodium: 1390,
    aliases: ["cfa", "chickfila", "chick fil a"],
  },
  {
    id: "preset-chickfila-nuggets-8",
    name: "Nuggets (8 pc)",
    brand: "Chick-fil-A",
    servingLabel: "8 pieces",
    calories: 250,
    protein: 27,
    carbs: 11,
    fat: 11,
    sodium: 1210,
    aliases: ["cfa nuggets"],
  },
  {
    id: "preset-popeyes-chicken-sandwich",
    name: "Classic Chicken Sandwich",
    brand: "Popeyes",
    servingLabel: "sandwich",
    calories: 700,
    protein: 28,
    carbs: 50,
    fat: 42,
    sugar: 7,
    sodium: 1440,
    aliases: ["popeye"],
  },
  {
    id: "preset-kfc-original-breast",
    name: "Original Recipe Chicken Breast",
    brand: "KFC",
    servingLabel: "piece",
    calories: 390,
    protein: 39,
    carbs: 11,
    fat: 21,
    sodium: 1190,
    aliases: ["fried chicken"],
  },
  {
    id: "preset-pizza-hut-pepperoni-slice-pan",
    name: "Pepperoni Pan Pizza slice",
    brand: "Pizza Hut",
    servingLabel: "slice",
    calories: 350,
    protein: 14,
    carbs: 32,
    fat: 18,
    sugar: 3,
    sodium: 780,
    aliases: ["pizza", "pepperoni"],
  },
  {
    id: "preset-dominos-pepperoni-hand-tossed",
    name: "Pepperoni Hand Tossed slice (med)",
    brand: "Domino's",
    servingLabel: "slice",
    calories: 280,
    protein: 12,
    carbs: 32,
    fat: 11,
    sugar: 3,
    sodium: 670,
    aliases: ["dominos", "pizza"],
  },
  {
    id: "preset-papa-johns-pepperoni-slice",
    name: "Pepperoni Pizza slice (large)",
    brand: "Papa Johns",
    servingLabel: "slice",
    calories: 360,
    protein: 14,
    carbs: 40,
    fat: 15,
    sugar: 5,
    sodium: 850,
    aliases: ["papa john's", "pizza"],
  },
  {
    id: "preset-starbucks-latte-grande",
    name: "Caffè Latte Grande (2% milk)",
    brand: "Starbucks",
    servingLabel: "grande",
    calories: 190,
    protein: 13,
    carbs: 18,
    fat: 7,
    sugar: 17,
    sodium: 170,
    aliases: ["latte", "coffee"],
  },
  {
    id: "preset-dunkin-bacon-egg-cheese",
    name: "Bacon Egg & Cheese on English Muffin",
    brand: "Dunkin'",
    servingLabel: "sandwich",
    calories: 390,
    protein: 17,
    carbs: 37,
    fat: 19,
    sugar: 3,
    sodium: 990,
    aliases: ["dunkin", "breakfast sandwich"],
  },
  {
    id: "preset-panera-broccoli-cheddar",
    name: "Broccoli Cheddar Soup (bowl)",
    brand: "Panera",
    servingLabel: "bowl",
    calories: 360,
    protein: 14,
    carbs: 30,
    fat: 21,
    sugar: 7,
    sodium: 1340,
    aliases: ["soup"],
  },
  {
    id: "preset-five-guys-cheeseburger",
    name: "Cheeseburger (regular)",
    brand: "Five Guys",
    servingLabel: "burger",
    calories: 840,
    protein: 47,
    carbs: 40,
    fat: 55,
    sugar: 9,
    sodium: 1050,
    aliases: ["5 guys", "fiveguys"],
  },
  {
    id: "preset-in-n-out-double-double",
    name: "Double-Double",
    brand: "In-N-Out",
    servingLabel: "burger",
    calories: 670,
    protein: 37,
    carbs: 41,
    fat: 41,
    sugar: 10,
    sodium: 1440,
    aliases: ["innout", "in n out", "double double"],
  },
  {
    id: "preset-shake-shack-single",
    name: "ShackBurger Single",
    brand: "Shake Shack",
    servingLabel: "burger",
    calories: 500,
    protein: 27,
    carbs: 26,
    fat: 31,
    sugar: 6,
    sodium: 1150,
    aliases: ["shack burger"],
  },
  {
    id: "preset-wingstop-classic-wings-6",
    name: "Classic Wings (6) + ranch",
    brand: "Wingstop",
    servingLabel: "6 wings",
    calories: 620,
    protein: 42,
    carbs: 4,
    fat: 48,
    sodium: 1400,
    aliases: ["wings"],
  },
  {
    id: "preset-panda-orange-chicken",
    name: "Orange Chicken (serving)",
    brand: "Panda Express",
    servingLabel: "serving",
    calories: 490,
    protein: 25,
    carbs: 51,
    fat: 23,
    sugar: 19,
    sodium: 820,
    aliases: ["panda", "orange chicken"],
  },
];
