/** Catalog of brand / common food presets (per serving). Fixed ids for idempotent seeding. */

import { PRESET_CATALOG_EXTRAS } from "./presetCatalogExtras.js";

export type CatalogPreset = {
  id: string;
  name: string;
  brand?: string;
  /** Display unit for amount (1 = one bottle/bar/cup as labeled). */
  servingLabel: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
  /** Extra terms for natural-language preset search. */
  aliases?: string[];
};

const PRESET_CATALOG_CORE: CatalogPreset[] = [
  // Protein drinks
  {
    id: "preset-fairlife-core-power-42",
    name: "Core Power Elite 42g",
    brand: "Fairlife",
    servingLabel: "bottle (414ml)",
    calories: 230,
    protein: 42,
    carbs: 5,
    fat: 2,
    sugar: 2,
    sodium: 260,
  },
  {
    id: "preset-fairlife-core-power-26",
    name: "Core Power 26g",
    brand: "Fairlife",
    servingLabel: "bottle (414ml)",
    calories: 170,
    protein: 26,
    carbs: 8,
    fat: 4.5,
    sugar: 6,
    sodium: 280,
  },
  {
    id: "preset-fairlife-nutrition-plan",
    name: "Nutrition Plan shake",
    brand: "Fairlife",
    servingLabel: "bottle (340ml)",
    calories: 150,
    protein: 30,
    carbs: 4,
    fat: 2.5,
    sugar: 2,
    sodium: 280,
  },
  {
    id: "preset-premier-chocolate",
    name: "Protein Shake Chocolate",
    brand: "Premier Protein",
    servingLabel: "shake (325ml)",
    calories: 160,
    protein: 30,
    carbs: 4,
    fat: 3,
    sugar: 1,
    fiber: 1,
    sodium: 190,
  },
  {
    id: "preset-premier-vanilla",
    name: "Protein Shake Vanilla",
    brand: "Premier Protein",
    servingLabel: "shake (325ml)",
    calories: 160,
    protein: 30,
    carbs: 3,
    fat: 3,
    sugar: 1,
    sodium: 190,
  },
  {
    id: "preset-muscle-milk-pro",
    name: "Pro Series shake",
    brand: "Muscle Milk",
    servingLabel: "bottle (414ml)",
    calories: 160,
    protein: 32,
    carbs: 2,
    fat: 2,
    sugar: 0,
    sodium: 230,
  },
  {
    id: "preset-orgain-organic",
    name: "Organic Protein shake",
    brand: "Orgain",
    servingLabel: "bottle (330ml)",
    calories: 160,
    protein: 20,
    carbs: 13,
    fat: 3,
    fiber: 2,
    sugar: 1,
    sodium: 210,
  },
  // Yogurt / dairy
  {
    id: "preset-chobani-zero-plain",
    name: "Zero Sugar Plain",
    brand: "Chobani",
    servingLabel: "cup (150g)",
    calories: 60,
    protein: 11,
    carbs: 4,
    fat: 0,
    sugar: 0,
    sodium: 50,
  },
  {
    id: "preset-chobani-complete",
    name: "Complete Vanilla",
    brand: "Chobani",
    servingLabel: "cup (150g)",
    calories: 130,
    protein: 20,
    carbs: 11,
    fat: 2.5,
    sugar: 6,
    sodium: 70,
  },
  {
    id: "preset-oikos-pro",
    name: "Pro Yogurt",
    brand: "Oikos",
    servingLabel: "cup (150g)",
    calories: 140,
    protein: 20,
    carbs: 14,
    fat: 0,
    sugar: 3,
    sodium: 50,
  },
  {
    id: "preset-fage-0-plain",
    name: "Total 0% Plain",
    brand: "Fage",
    servingLabel: "cup (170g)",
    calories: 90,
    protein: 18,
    carbs: 5,
    fat: 0,
    sugar: 5,
    sodium: 65,
  },
  {
    id: "preset-siggis-plain",
    name: "Plant-Based / Skyr style Plain",
    brand: "Siggi's",
    servingLabel: "cup (150g)",
    calories: 100,
    protein: 15,
    carbs: 9,
    fat: 0,
    sugar: 4,
    sodium: 55,
  },
  // Bars
  {
    id: "preset-quest-cookie-cream",
    name: "Protein Bar Cookies & Cream",
    brand: "Quest",
    servingLabel: "bar (60g)",
    calories: 190,
    protein: 21,
    carbs: 21,
    fat: 8,
    fiber: 14,
    sugar: 1,
    sodium: 220,
  },
  {
    id: "preset-quest-hero",
    name: "Hero Bar Chocolate Caramel",
    brand: "Quest",
    servingLabel: "bar (60g)",
    calories: 160,
    protein: 15,
    carbs: 24,
    fat: 7,
    fiber: 14,
    sugar: 1,
    sodium: 190,
  },
  {
    id: "preset-rxbar-chocolate",
    name: "Protein Bar Chocolate Sea Salt",
    brand: "RXBAR",
    servingLabel: "bar (52g)",
    calories: 210,
    protein: 12,
    carbs: 23,
    fat: 9,
    fiber: 5,
    sugar: 13,
    sodium: 270,
  },
  {
    id: "preset-built-puff",
    name: "Puff Bar",
    brand: "Built",
    servingLabel: "bar",
    calories: 130,
    protein: 17,
    carbs: 13,
    fat: 2.5,
    fiber: 6,
    sugar: 4,
    sodium: 90,
  },
  {
    id: "preset-one-bar",
    name: "ONE Bar Birthday Cake",
    brand: "ONE",
    servingLabel: "bar (60g)",
    calories: 220,
    protein: 20,
    carbs: 23,
    fat: 8,
    fiber: 1,
    sugar: 1,
    sodium: 160,
  },
  {
    id: "preset-kind-protein",
    name: "Protein Crunchy Peanut Butter",
    brand: "KIND",
    servingLabel: "bar (50g)",
    calories: 250,
    protein: 12,
    carbs: 17,
    fat: 17,
    fiber: 5,
    sugar: 8,
    sodium: 125,
  },
  // Staples
  {
    id: "preset-eggs-3",
    name: "Eggs (large)",
    brand: "Staple",
    servingLabel: "egg",
    calories: 70,
    protein: 6,
    carbs: 0,
    fat: 5,
    sodium: 70,
  },
  {
    id: "preset-chicken-breast-100g",
    name: "Chicken breast cooked",
    brand: "Staple",
    servingLabel: "100g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    sodium: 74,
  },
  {
    id: "preset-white-rice-100g",
    name: "White rice cooked",
    brand: "Staple",
    servingLabel: "100g",
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    sodium: 1,
  },
  {
    id: "preset-brown-rice-100g",
    name: "Brown rice cooked",
    brand: "Staple",
    servingLabel: "100g",
    calories: 112,
    protein: 2.3,
    carbs: 24,
    fat: 0.8,
    fiber: 1.8,
    sodium: 5,
  },
  {
    id: "preset-oats-40g",
    name: "Rolled oats dry",
    brand: "Staple",
    servingLabel: "40g (½ cup)",
    calories: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    fiber: 4,
    sugar: 1,
    sodium: 0,
  },
  {
    id: "preset-banana",
    name: "Banana",
    brand: "Staple",
    servingLabel: "medium",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    fiber: 3,
    sugar: 14,
    sodium: 1,
  },
  {
    id: "preset-apple",
    name: "Apple",
    brand: "Staple",
    servingLabel: "medium",
    calories: 95,
    protein: 0.5,
    carbs: 25,
    fat: 0.3,
    fiber: 4,
    sugar: 19,
    sodium: 2,
  },
  {
    id: "preset-avocado-half",
    name: "Avocado",
    brand: "Staple",
    servingLabel: "half",
    calories: 120,
    protein: 1.5,
    carbs: 6,
    fat: 11,
    fiber: 5,
    sodium: 5,
  },
  {
    id: "preset-peanut-butter-tbsp",
    name: "Peanut butter",
    brand: "Staple",
    servingLabel: "tbsp (16g)",
    calories: 95,
    protein: 4,
    carbs: 3,
    fat: 8,
    fiber: 1,
    sugar: 1,
    sodium: 70,
  },
  {
    id: "preset-whey-scoop",
    name: "Whey protein powder",
    brand: "Generic",
    servingLabel: "scoop (~30g)",
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1.5,
    sugar: 2,
    sodium: 50,
  },
  {
    id: "preset-almond-milk-cup",
    name: "Unsweetened almond milk",
    brand: "Staple",
    servingLabel: "cup (240ml)",
    calories: 30,
    protein: 1,
    carbs: 1,
    fat: 2.5,
    sodium: 150,
  },
  {
    id: "preset-whole-milk-cup",
    name: "Whole milk",
    brand: "Staple",
    servingLabel: "cup (240ml)",
    calories: 150,
    protein: 8,
    carbs: 12,
    fat: 8,
    sugar: 12,
    sodium: 105,
  },
  {
    id: "preset-bread-slice",
    name: "Whole wheat bread",
    brand: "Staple",
    servingLabel: "slice",
    calories: 80,
    protein: 4,
    carbs: 14,
    fat: 1,
    fiber: 2,
    sugar: 2,
    sodium: 140,
  },
  {
    id: "preset-salmon-100g",
    name: "Salmon cooked",
    brand: "Staple",
    servingLabel: "100g",
    calories: 208,
    protein: 22,
    carbs: 0,
    fat: 13,
    sodium: 59,
  },
  {
    id: "preset-turkey-deli-100g",
    name: "Turkey breast deli",
    brand: "Staple",
    servingLabel: "100g",
    calories: 104,
    protein: 17,
    carbs: 2,
    fat: 2,
    sodium: 650,
  },
  {
    id: "preset-cottage-lowfat",
    name: "Cottage cheese 1%",
    brand: "Staple",
    servingLabel: "½ cup (113g)",
    calories: 80,
    protein: 14,
    carbs: 3,
    fat: 1,
    sugar: 3,
    sodium: 350,
  },
  {
    id: "preset-creatine-5g",
    name: "Creatine monohydrate",
    brand: "Supplement",
    servingLabel: "5g",
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
  },
  // More protein / RTD
  {
    id: "preset-optimum-gold-standard",
    name: "Gold Standard Whey",
    brand: "Optimum Nutrition",
    servingLabel: "scoop (30g)",
    calories: 120,
    protein: 24,
    carbs: 3,
    fat: 1,
    sugar: 1,
    sodium: 130,
  },
  {
    id: "preset-ghost-whey",
    name: "Whey Protein",
    brand: "Ghost",
    servingLabel: "scoop (33g)",
    calories: 130,
    protein: 25,
    carbs: 3,
    fat: 1.5,
    sugar: 2,
    sodium: 150,
  },
  {
    id: "preset-alani-protein",
    name: "Fit Shake",
    brand: "Alani Nu",
    servingLabel: "bottle (355ml)",
    calories: 140,
    protein: 20,
    carbs: 5,
    fat: 3.5,
    sugar: 1,
    sodium: 200,
  },
  {
    id: "preset-ensure-max",
    name: "Max Protein",
    brand: "Ensure",
    servingLabel: "bottle (330ml)",
    calories: 150,
    protein: 30,
    carbs: 7,
    fat: 1.5,
    sugar: 4,
    sodium: 230,
  },
  {
    id: "preset-boost-high-protein",
    name: "High Protein",
    brand: "Boost",
    servingLabel: "bottle (237ml)",
    calories: 240,
    protein: 20,
    carbs: 26,
    fat: 6,
    sugar: 12,
    sodium: 190,
  },
  {
    id: "preset-iconic-protein",
    name: "Protein Drink Chocolate",
    brand: "Iconic",
    servingLabel: "bottle (330ml)",
    calories: 140,
    protein: 20,
    carbs: 8,
    fat: 3.5,
    sugar: 4,
    sodium: 180,
  },
  {
    id: "preset-kirkland-protein",
    name: "Protein Shake Chocolate",
    brand: "Kirkland",
    servingLabel: "shake (325ml)",
    calories: 160,
    protein: 30,
    carbs: 4,
    fat: 3,
    sugar: 1,
    sodium: 210,
  },
  // Energy / drinks
  {
    id: "preset-celsius-live-fit",
    name: "Live Fit",
    brand: "Celsius",
    servingLabel: "can (355ml)",
    calories: 10,
    protein: 0,
    carbs: 2,
    fat: 0,
    sugar: 0,
    sodium: 10,
  },
  {
    id: "preset-monster-zero",
    name: "Zero Ultra",
    brand: "Monster",
    servingLabel: "can (473ml)",
    calories: 10,
    protein: 0,
    carbs: 3,
    fat: 0,
    sugar: 0,
    sodium: 210,
  },
  {
    id: "preset-redbull-sugarfree",
    name: "Sugar Free",
    brand: "Red Bull",
    servingLabel: "can (250ml)",
    calories: 10,
    protein: 0,
    carbs: 3,
    fat: 0,
    sugar: 0,
    sodium: 105,
  },
  {
    id: "preset-gatorade-zero",
    name: "Zero Glacier Freeze",
    brand: "Gatorade",
    servingLabel: "bottle (591ml)",
    calories: 5,
    protein: 0,
    carbs: 1,
    fat: 0,
    sugar: 0,
    sodium: 270,
  },
  {
    id: "preset-liquid-iv",
    name: "Hydration Multiplier",
    brand: "Liquid I.V.",
    servingLabel: "packet",
    calories: 45,
    protein: 0,
    carbs: 11,
    fat: 0,
    sugar: 11,
    sodium: 500,
  },
  // More bars / snacks
  {
    id: "preset-clif-builder",
    name: "Builder's Chocolate",
    brand: "Clif",
    servingLabel: "bar (68g)",
    calories: 280,
    protein: 20,
    carbs: 30,
    fat: 9,
    fiber: 3,
    sugar: 17,
    sodium: 230,
  },
  {
    id: "preset-pure-protein-bar",
    name: "Chocolate Deluxe",
    brand: "Pure Protein",
    servingLabel: "bar (50g)",
    calories: 180,
    protein: 20,
    carbs: 17,
    fat: 5,
    fiber: 0,
    sugar: 2,
    sodium: 190,
  },
  {
    id: "preset-nature-valley-protein",
    name: "Protein Peanut Butter Dark Chocolate",
    brand: "Nature Valley",
    servingLabel: "bar (40g)",
    calories: 190,
    protein: 10,
    carbs: 14,
    fat: 12,
    fiber: 5,
    sugar: 6,
    sodium: 180,
  },
  {
    id: "preset-think!-high-protein",
    name: "High Protein Creamy Peanut Butter",
    brand: "think!",
    servingLabel: "bar (60g)",
    calories: 230,
    protein: 20,
    carbs: 24,
    fat: 8,
    fiber: 5,
    sugar: 0,
    sodium: 210,
  },
  {
    id: "preset-ratio-yogurt",
    name: "Protein Yogurt Vanilla",
    brand: "Ratio",
    servingLabel: "cup (150g)",
    calories: 170,
    protein: 25,
    carbs: 7,
    fat: 5,
    sugar: 2,
    sodium: 70,
  },
  {
    id: "preset-two-good-yogurt",
    name: "Lower Sugar Vanilla",
    brand: "Two Good",
    servingLabel: "cup (150g)",
    calories: 80,
    protein: 12,
    carbs: 3,
    fat: 2,
    sugar: 2,
    sodium: 45,
  },
  {
    id: "preset-dave-killer-bread",
    name: "21 Whole Grains",
    brand: "Dave's Killer Bread",
    servingLabel: "slice",
    calories: 110,
    protein: 5,
    carbs: 22,
    fat: 1.5,
    fiber: 5,
    sugar: 5,
    sodium: 170,
  },
  {
    id: "preset-ezekiel-bread",
    name: "Sprouted Whole Grain",
    brand: "Food for Life",
    servingLabel: "slice",
    calories: 80,
    protein: 4,
    carbs: 15,
    fat: 0.5,
    fiber: 3,
    sugar: 0,
    sodium: 75,
  },
  {
    id: "preset-egglife-wrap",
    name: "Egg White Wrap",
    brand: "Egglife",
    servingLabel: "wrap",
    calories: 30,
    protein: 5,
    carbs: 0,
    fat: 0,
    sodium: 160,
  },
  {
    id: "preset-mission-carb-balance",
    name: "Carb Balance Tortilla Soft Taco",
    brand: "Mission",
    servingLabel: "tortilla",
    calories: 70,
    protein: 5,
    carbs: 19,
    fat: 3.5,
    fiber: 15,
    sugar: 0,
    sodium: 360,
  },
  {
    id: "preset-beyond-burger",
    name: "Beyond Burger patty",
    brand: "Beyond Meat",
    servingLabel: "patty (113g)",
    calories: 230,
    protein: 20,
    carbs: 7,
    fat: 14,
    fiber: 2,
    sugar: 0,
    sodium: 390,
  },
  {
    id: "preset-impossible-burger",
    name: "Impossible Burger patty",
    brand: "Impossible",
    servingLabel: "patty (113g)",
    calories: 240,
    protein: 19,
    carbs: 9,
    fat: 14,
    fiber: 3,
    sugar: 1,
    sodium: 370,
  },
  {
    id: "preset-trader-joe-egg-bites",
    name: "Sous Vide Egg Bites Bacon",
    brand: "Trader Joe's",
    servingLabel: "2 bites",
    calories: 170,
    protein: 12,
    carbs: 4,
    fat: 12,
    sugar: 2,
    sodium: 420,
  },
  {
    id: "preset-starbucks-egg-bites",
    name: "Bacon & Gruyère Egg Bites",
    brand: "Starbucks",
    servingLabel: "2 bites",
    calories: 300,
    protein: 19,
    carbs: 9,
    fat: 20,
    sugar: 1,
    sodium: 660,
  },
  {
    id: "preset-chipotle-chicken",
    name: "Chicken (burrito bowl)",
    brand: "Chipotle",
    servingLabel: "serving (~113g)",
    calories: 180,
    protein: 32,
    carbs: 0,
    fat: 7,
    sodium: 310,
  },
  {
    id: "preset-chipotle-cilantro-rice",
    name: "Cilantro-Lime White Rice",
    brand: "Chipotle",
    servingLabel: "serving",
    calories: 210,
    protein: 4,
    carbs: 40,
    fat: 4,
    sodium: 350,
  },
  {
    id: "preset-chipotle-black-beans",
    name: "Black Beans",
    brand: "Chipotle",
    servingLabel: "serving",
    calories: 130,
    protein: 8,
    carbs: 22,
    fat: 1.5,
    fiber: 8,
    sugar: 1,
    sodium: 290,
  },
];

export const PRESET_CATALOG: CatalogPreset[] = [...PRESET_CATALOG_CORE, ...PRESET_CATALOG_EXTRAS];
